#!/bin/sh
LOCPROG=$PWD/$1
LOCTEST=$PWD/$2

if [ ! -f $LOCPROG ] || [ ! -x $LOCPROG ]; then
  echo 'Erro: O programa nao existe ou nao eh executavel'
  exit 1
fi

if [ ! -d $LOCTEST ] || [ ! $(basename $LOCTEST) = "$2" ]; then
  echo 'Erro: Pasta nao encontrada ou nao especificada'
  exit 1
fi

if [ ! -d $PWD/CCheckOutput ]; then
  mkdir CCheckOutput
fi

LOCOUT=$PWD/CCheckOutput
cd $LOCTEST

for testCase in input*; do
  $LOCPROG < $testCase > $LOCOUT/$testCase
done

i=1
while [ "$i" -le 10 ]; do
  mv $LOCOUT/input$i.txt $LOCOUT/output$i.txt
  i=$(( $i + 1 ))
  done

for compareOutput in output*; do
  diff $LOCOUT/$compareOutput $compareOutput > /dev/null 2>/dev/null
  if [ $? = 0 ]; then
    echo $compareOutput '\033[32mPASSOU\033[0m'
  elif [ $? = 1 ]; then
    echo $compareOutput '\033[31mFALHOU\033[0m'
  else
    echo 'Erro: algum arquivo de saida nao existe ou nao pode ser acessado'
    exit 1
  fi
done
